name: Postman Tests Pipeline

# 1. Trigger when code is pushed to a specific branch or Postman script changes
on:
  push:
    branches:
      - 'main' # Replace with the name of your specific branch
    paths:
      - 'postman/*.json'  # Path to your Postman collection and environment files (or adjust as per your repo structure)
      - '**/*.js'         # Path to trigger when any code changes

  workflow_dispatch:  # Add this to enable manual triggering of the workflow

jobs:
  run_newman_tests:  # Correct indentation here
    runs-on: ubuntu-latest

    steps:
      # 2. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 3. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 4. Install Newman
      - name: Install Newman
        run: npm install -g newman

      # 5. Execute Newman to run Postman tests
      - name: Run Postman collection tests with Newman
        run: |
          newman run postman/BaaS_Dev.postman_collection.json \
            --folder "IntegrationTests" \
            -e postman/DevelopmentConsolidated.postman_environment.json \
            --reporters cli,junit \
            --reporter-junit-export results.xml

      # 6. Mark the workflow status green or red based on test results
      - name: Set status based on Newman result (failure)
        if: failure()
        run: echo "Some tests have failed. Check the results."

      - name: Set status based on Newman result (success)
        if: success()
        run: echo "All tests passed successfully!"
